apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "operator.fullname" . }}-csi-node
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: csi-node
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: csi-node
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}-csi
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "operator.appname" . }}-csi-node
          image: "{{ .Values.image.csiDriver.repository }}:{{ .Values.image.csiDriver.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.csiDriver.pullPolicy }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - --health-probe-bind-address={{ .Values.csiNode.healthProbe.bindAddress }}
            {{- if .Values.csiNode.metrics.enabled }}
            {{- $metricsPort := include "operator.metricsPort" .Values.csiNode.metrics }}
            - --metrics-bind-address=:{{ $metricsPort }}
            {{- if .Values.csiNode.metrics.secure }}
            - --metrics-secure=true
            {{- end }}
            {{- end }}
            - -endpoint=$(ADDRESS)
            - -nodeid=$(NODE_NAME)
            - -zap-log-level={{ .Values.csiNode.logLevel | default 2 }}
          ports:
            {{- if .Values.csiNode.metrics.enabled }}
            {{- $metricsScheme := include "operator.metricsScheme" .Values.csiNode.metrics }}
            {{- $metricsPort := include "operator.metricsPort" .Values.csiNode.metrics }}
            - containerPort: {{ $metricsPort }}
              name: {{ $metricsScheme }}
              protocol: TCP
            {{- end }}
            {{- $healthPort := include "operator.healthProbePort" .Values.csiNode.healthProbe }}
            - containerPort: {{ $healthPort }}
              name: health
              protocol: TCP
          resources:
            {{- .Values.csiNode.resources | toYaml | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ $healthPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ $healthPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          securityContext:
            {{- toYaml .Values.csiNode.securityContext | nindent 12 }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletDir }}/pods
              mountPropagation: Bidirectional
        - name: node-driver-registrar
          image: "{{ .Values.image.csiNodeDriverRegistrar.repository }}:{{ .Values.image.csiNodeDriverRegistrar.tag }}"
          imagePullPolicy: {{ .Values.image.csiNodeDriverRegistrar.pullPolicy }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/secrets.kubedoop.dev/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v={{ .Values.csiNodeDriverRegistrar.logLevel | default 2 }}
          resources:
            {{- .Values.csiNodeDriverRegistrar.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: {{ .Values.image.livenessProbe.repository }}:{{ .Values.image.livenessProbe.tag }}
          imagePullPolicy: {{ .Values.image.livenessProbe.pullPolicy }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --health-port=9808
            - --probe-timeout=3s
            - --v={{ .Values.livenessProbe.logLevel | default 2 }}
          resources:
            {{- .Values.livenessProbe.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: 9808
              name: healthz
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: registration-dir
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            path: {{ .Values.kubeletDir }}/plugins_registry
            type: DirectoryOrCreate
        - name: socket-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins/secrets.kubedoop.dev/
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/pods/
            type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
