apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
metadata:
  name: {{ include "operator.fullname" . }}-leader-election
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}-csi
  namespace: {{ .Release.Namespace }}
